name: CI Simple Tuner

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v1
        with: { version: 3.x }

      - name: Install dependencies
        run: |
          sudo apt-get install libxrandr-dev libxinerama-dev libxcursor-dev clang llvm
          python -m pip install -r requirements.lock.txt

      - name: Install sonar-scanner
        uses: SonarSource/sonarcloud-github-c-cpp@v2

      - name: Build
        run: task ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          CXX: /usr/bin/clang++
          CC: /usr/bin/clang

      - name: Test
        run: task test

      - name: Report & Analysis
        run: task report-and-analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

